language: php

cache:
  directories:
    - $HOME/.composer
    - vendor

php:
 - 7.1
 - 7.0
 - 5.6
 - hhvm
 - nightly

env:
 matrix:
  - PHPUNIT_VERSION=^5.0 SUITE=5
  - PHPUNIT_VERSION=^6.0 SUITE=6

before_install:
 - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* && "$TRAVIS_PHP_VERSION" != *"7.1"* ]]; then phpenv config-rm xdebug.ini; else mkdir -p ~/.phpenv/versions/hhvm/etc; fi;'
 - echo "date.timezone = Europe/London" >> .date-timezone.ini && phpenv config-add .date-timezone.ini

before_script:
 - composer self-update
 - composer install
 - composer require "phpunit/phpunit:$PHPUNIT_VERSION"
 - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* && "$TRAVIS_PHP_VERSION" != *"7.1"* ]]; then echo "zend_extension = xdebug.so" >> .xdebug.ini && phpenv config-add .xdebug.ini; fi;'

script:
 - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* && "$TRAVIS_PHP_VERSION" != *"7.1"* ]]; then vendor/bin/phpunit --coverage-clover coverage.xml --testsuite $SUITE; else vendor/bin/phpunit --testsuite $SUITE; fi;'

after_success:
 - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* && "$TRAVIS_PHP_VERSION" != *"7.1"* ]]; then chmod 777 coverage.xml && bash <(curl -s https://codecov.io/bash); fi;'

notifications:
 on_success: change
 on_failure: always

matrix:
  fast_finish: true
  allow_failures:
   - php: nightly
