language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
 - 7.0
 - 5.6
 - hhvm
 - nightly

before_install:
 - git config --global user.name Alorel
 - git config --global user.email a.molcanovas@gmail.com

before_script:
 - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then phpenv config-rm xdebug.ini; else mkdir -p ~/.phpenv/versions/hhvm/etc; fi;'
 - echo "date.timezone = Europe/London" >> .date-timezone.ini && phpenv config-add .date-timezone.ini
 - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then echo "zend_extension = xdebug.so" >> .xdebug.ini && phpenv config-add .xdebug.ini; fi;'

script:
# - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then vendor/bin/phpunit --coverage-clover coverage.xml --testsuite $SUITE && chmod 777 coverage.xml && bash <(curl -s https://codecov.io/bash); fi;'
# - bash -c 'if [[ "$TRAVIS_PHP_VERSION" == *"hhvm"* ]]; then vendor/bin/phpunit --testsuite $SUITE; fi;'
 - vendor/bin/phpunit

notifications:
 on_success: change
 on_failure: always

matrix:
  fast_finish: true
  allow_failures:
   - php: nightly
